### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by webcracy** [nu7hatch/gmail#105]
# Suggested Roadmap

Here's a proposal to organise ourselves to deal with open PR's. Please share your  thoughts.

Could contributors start tagging issues as well? That would be awesome. Cc: @nu7hatch, @jgrevich , @johnnyshields.

Meanwhile I'll edit this post according to further suggestions, votes and ideas.

## ~~v0.4.1 - Fix fresh installs~~
* [x] MIME dependency fix (#109)
* [x] gitignore Gemfile.lock (#100)
* [x] cherry-pick 8fc82e8 from (#66)
* [x] Get all tests passing in 1.8.7

## v0.5.0 - Return of the Jedi
* [x] Last version compatible with ~~Ruby 1.8.7~~ and 1.9.3
* [x] Add Ruby 2.X support 
* [x] Ruby 1.9.3 IMAP Extensions fix (use #66, provided it's patched as per the comments)
* [x] XOAuth 2 support (use #80, make sure the change in `account.yml` for testing is explained in 
README)
* [x] Localised labels, better character support (use #83 and #82) -> #110
* [ ] Better test coverage (use #75, #102 and #103)
* [ ] Fix label addition/removal (in #102)
* [ ] Investigate other issues and pull requests referenced in #96 

## v0.5.1 - A New Hope
* [ ] Drop Ruby 1.x support
* [ ] `#idle` command support (start with #93)
* [ ] Other stuff...

**Comment by jcarbo** [comment]
@johnnyshields @webcracy @jgrevich - any updates here?

I'm relying pretty heavily on this gem so I'm pretty keen to keep the ball rolling on this roadmap. Happy to help fix bugs, review PRs, etc. There are a bunch of open PRs and not much activity so just wanted to check this repo was still alive before I invested a lot of time.

**Comment by johnnyshields** [comment]
@jcarbo I agree we need to get rolling here. I think the first thing to do is that we should get as many tests merged into master as possible, and get Travis setup--I have a PR for that. This will give us confidence to begin pulling in bugfixes.

@webcracy for the sake of expediency I think we should also fully drop 1.8.7 support at this time, in other words we should skip ahead to your proposed version 0.5.0. If someone needs 1.8.7 support they can use the currently released version. We should keep 1.9.3 however. Agreed?

**Comment by johnnyshields** [comment]
@jcarbo thanks for offering to help by the way. Like you my business also depends heavily on this gem.

**Comment by weshatheleopard** [comment]
Could you guys please release the new version of the gem with all the fixes that are already merged in? A bit overdue...

**Comment by bootstraponline** [comment]
In the interest of moving things along, I added the repo to the new gmailgem organization. #131

https://github.com/gmailgem/gmail

**Comment by johnnyshields** [comment]
@weshatheleopard I'd to give it a week with people using it on master to shake out any issues. Also any help writing specs would be greatly appreciated.
